// export interface Product {
//   id: string;
//   reference: string;
//   name: string;
//   category:
//     | "Tóner"
//     | "Tinta"
//     | "Drum"
//     | "Material POP"
//     | "Insumos"
//     | "Accesorio";
//   brand: string;
//   description: string;
//   image: string;
// }

// export const ASTA_PRODUCTS: Product[] = [
//   // --- PÁGINA 1 ---
//   {
//     id: "1",
//     reference: "A-006R04387",
//     name: "ASTA TONER XEROX CLINE STD BLACK DMO",
//     category: "Tóner",
//     brand: "Xerox",
//     description: "Tóner premium de alta densidad.",
//     image: "/productos/1.jpg",
//   },
//   {
//     id: "2",
//     reference: "A-006R04388",
//     name: "ASTA TONER XEROX CLINE STD CYAN DMO",
//     category: "Tóner",
//     brand: "Xerox",
//     description: "Cartucho cian de alta fidelidad.",
//     image: "/productos/2.jpg",
//   },
//   {
//     id: "3",
//     reference: "A-006R04389",
//     name: "ASTA TONER XEROX CLINE STD MAGENTA DMO",
//     category: "Tóner",
//     brand: "Xerox",
//     description: "Cartucho magenta premium.",
//     image: "/productos/3.jpg",
//   },
//   {
//     id: "4",
//     reference: "A-006R04390",
//     name: "ASTA TONER XEROX CLINE STD YELLOW DMO",
//     category: "Tóner",
//     brand: "Xerox",
//     description: "Cartucho amarillo de alto brillo.",
//     image: "/productos/4.jpg",
//   },
//   {
//     id: "5",
//     reference: "A-006R04403",
//     name: "ASTA TONER XEROX NEGRO MOHAVE B230/B225",
//     category: "Tóner",
//     brand: "Xerox",
//     description: "Compatible con serie Mohave.",
//     image: "/productos/5.jpg",
//   },
//   {
//     id: "6",
//     reference: "A-057H",
//     name: "ASTA TONER CANON CRG 057H CON CHIP",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Alto rendimiento con chip inteligente.",
//     image: "/productos/6.jpg",
//   },
//   {
//     id: "7",
//     reference: "A-544C",
//     name: "ASTA TINTA EPSON CYAN",
//     category: "Tinta",
//     brand: "Epson",
//     description: "Botella de tinta cian para EcoTank.",
//     image: "/productos/7.jpg",
//   },
//   {
//     id: "8",
//     reference: "A-544M",
//     name: "ASTA TINTA EPSON MAGENTA",
//     category: "Tinta",
//     brand: "Epson",
//     description: "Tinta magenta de alta calidad.",
//     image: "/productos/8.jpg",
//   },
//   {
//     id: "9",
//     reference: "A-544Y",
//     name: "ASTA TINTA EPSON YELLOW",
//     category: "Tinta",
//     brand: "Epson",
//     description: "Tinta amarilla para recargas precisas.",
//     image: "/productos/9.jpg",
//   },
//   {
//     id: "10",
//     reference: "A-664BK",
//     name: "ASTA TINTA EPSON NEGRO",
//     category: "Tinta",
//     brand: "Epson",
//     description: "Negro pigmentado duradero.",
//     image: "/productos/10.jpg",
//   },
//   {
//     id: "11",
//     reference: "A-664C",
//     name: "ASTA TINTA EPSON CYAN",
//     category: "Tinta",
//     brand: "Epson",
//     description: "Cian para impresión fotográfica.",
//     image: "/productos/11.jpg",
//   },
//   {
//     id: "12",
//     reference: "A-664M",
//     name: "ASTA TINTA EPSON MAGENTA",
//     category: "Tinta",
//     brand: "Epson",
//     description: "Magenta premium serie 664.",
//     image: "/productos/12.jpg",
//   },
//   {
//     id: "13",
//     reference: "A-664Y",
//     name: "ASTA TINTA EPSON YELLOW",
//     category: "Tinta",
//     brand: "Epson",
//     description: "Amarillo serie 664.",
//     image: "/productos/13.jpg",
//   },
//   {
//     id: "14",
//     reference: "A-CB435A-CE278A",
//     name: "ASTA TONER CB435A/CB436A/CE278A/285",
//     category: "Tóner",
//     brand: "HP",
//     description: "Multicompatible para LaserJet.",
//     image: "/productos/14.jpg",
//   },
//   {
//     id: "15",
//     reference: "A-CE255A",
//     name: "ASTA TONER HP CE255A LASERJET",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para serie LaserJet P3010/P3015.",
//     image: "/productos/15.jpg",
//   },
//   {
//     id: "16",
//     reference: "A-CE310A-CF350A",
//     name: "ASTA TONER CE310A-CF350A NEGRO",
//     category: "Tóner",
//     brand: "HP",
//     description: "Negro para Color LaserJet.",
//     image: "/productos/16.jpg",
//   },
//   {
//     id: "17",
//     reference: "A-CE311A-CF351A",
//     name: "ASTA TONER CE311A-CF351A CYAN",
//     category: "Tóner",
//     brand: "HP",
//     description: "Cian para Color LaserJet.",
//     image: "/productos/17.jpg",
//   },
//   {
//     id: "18",
//     reference: "A-CE312A-CF352A",
//     name: "ASTA TONER CE312A-CF352A YELLOW",
//     category: "Tóner",
//     brand: "HP",
//     description: "Amarillo para Color LaserJet.",
//     image: "/productos/18.jpg",
//   },
//   {
//     id: "19",
//     reference: "A-CE313A-CF353A",
//     name: "ASTA TONER CE313A-CF353A MAGENTA",
//     category: "Tóner",
//     brand: "HP",
//     description: "Magenta para Color LaserJet.",
//     image: "/productos/19.jpg",
//   },
//   {
//     id: "20",
//     reference: "A-CE320A-CB540A",
//     name: "ASTA TONER CE320A-CB540A NEGRO",
//     category: "Tóner",
//     brand: "HP",
//     description: "Serie CP1215/CP1515/CP1525.",
//     image: "/productos/20.jpg",
//   },

//   // --- PÁGINA 2 ---
//   {
//     id: "21",
//     reference: "A-CF217A",
//     name: "ASTA TONER CF217A NEGRO",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para LaserJet Pro M102/M130.",
//     image: "/productos/21.jpg",
//   },
//   {
//     id: "22",
//     reference: "A-CF219A",
//     name: "ASTA DRUM CF219A",
//     category: "Drum",
//     brand: "HP",
//     description: "Cilindro de imagen LaserJet Pro.",
//     image: "/productos/22.jpg",
//   },
//   {
//     id: "23",
//     reference: "A-CF226ACRG052",
//     name: "ASTA TONER CF226A/CRG-052 NEGRO",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para LaserJet M402/M426.",
//     image: "/productos/23.jpg",
//   },
//   {
//     id: "24",
//     reference: "A-CF230A",
//     name: "ASTA TONER CF230A NEGRO/051 CANON",
//     category: "Tóner",
//     brand: "HP",
//     description: "Compatible HP y Canon.",
//     image: "/productos/24.jpg",
//   },
//   {
//     id: "25",
//     reference: "A-CF258A",
//     name: "ASTA TONER CF258A NEGRO NO CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Versión sin chip para M404.",
//     image: "/productos/25.jpg",
//   },
//   {
//     id: "26",
//     reference: "A-CF258ACC",
//     name: "ASTA TONER CF258 CON CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Incluye chip para serie M404/M428.",
//     image: "/productos/26.jpg",
//   },
//   {
//     id: "27",
//     reference: "A-CF280-CE505A",
//     name: "ASTA TONER CF280-CE505A",
//     category: "Tóner",
//     brand: "HP",
//     description: "Doble compatibilidad 05A/80A.",
//     image: "/productos/27.jpg",
//   },
//   {
//     id: "28",
//     reference: "A-CF283A",
//     name: "ASTA TONER CF283A NEGRO",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para LaserJet Pro M127/M125.",
//     image: "/productos/28.jpg",
//   },
//   {
//     id: "29",
//     reference: "A-CF411A-CH",
//     name: "ASTA TONER CON CHIP CF411A CYAN",
//     category: "Tóner",
//     brand: "HP",
//     description: "Color LaserJet Pro M452.",
//     image: "/productos/29.jpg",
//   },
//   {
//     id: "30",
//     reference: "A-CF412A-CH",
//     name: "ASTA TONER CON CHIP CF412A YELLOW",
//     category: "Tóner",
//     brand: "HP",
//     description: "Color LaserJet Pro M452.",
//     image: "/productos/30.jpg",
//   },
//   {
//     id: "31",
//     reference: "A-CF413A-CH",
//     name: "ASTA TONER CON CHIP CF413A MAGENTA",
//     category: "Tóner",
//     brand: "HP",
//     description: "Color LaserJet Pro M452.",
//     image: "/productos/31.jpg",
//   },
//   {
//     id: "32",
//     reference: "A-CF501A",
//     name: "ASTA TONER CF501A CYAN/CRG-054C",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para M254/M281.",
//     image: "/productos/32.jpg",
//   },
//   {
//     id: "33",
//     reference: "A-CF502A",
//     name: "ASTA TONER CF502A YELLOW",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para M254/M281.",
//     image: "/productos/33.jpg",
//   },
//   {
//     id: "34",
//     reference: "A-CF503A",
//     name: "ASTA TONER CF503A MAGENTA",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para M254/M281.",
//     image: "/productos/34.jpg",
//   },
//   {
//     id: "35",
//     reference: "A-CF510A",
//     name: "ASTA TONER CF510A NEGRO",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para LaserJet Pro M154/M180.",
//     image: "/productos/35.jpg",
//   },
//   {
//     id: "36",
//     reference: "A-CF511A",
//     name: "ASTA TONER CF511A CYAN",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para LaserJet Pro M154/M180.",
//     image: "/productos/36.jpg",
//   },
//   {
//     id: "37",
//     reference: "A-CF512A",
//     name: "ASTA TONER CF512A YELLOW",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para LaserJet Pro M154/M180.",
//     image: "/productos/37.jpg",
//   },
//   {
//     id: "38",
//     reference: "A-CF513A",
//     name: "ASTA TONER CF513A MAGENTA",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para LaserJet Pro M154/M180.",
//     image: "/productos/38.jpg",
//   },
//   {
//     id: "39",
//     reference: "A-CHIP-W1105-105A",
//     name: "ASTA CHIP W1105A/105A V3",
//     category: "Insumos",
//     brand: "HP",
//     description: "Chip de repuesto para 105A.",
//     image: "/productos/39.jpg",
//   },
//   {
//     id: "40",
//     reference: "A-CRG-054BK",
//     name: "ASTA TONER CANON CRG-054 BK NEGRO",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Negro serie ImageCLASS.",
//     image: "/productos/40.jpg",
//   },

//   // --- PÁGINA 3 ---
//   {
//     id: "41",
//     reference: "A-CRG-055BK",
//     name: "ASTA TONER CRG-055BK NO CHIP",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Serie MF741/MF743.",
//     image: "/productos/41.jpg",
//   },
//   {
//     id: "42",
//     reference: "A-CRG-055BK-CH",
//     name: "ASTA TONER CRG-055BK CON CHIP",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Listo para usar serie MF741.",
//     image: "/productos/42.jpg",
//   },
//   {
//     id: "43",
//     reference: "A-CRG-055C",
//     name: "ASTA TONER CRG-055C NO CHIP",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Cian serie MF741.",
//     image: "/productos/43.jpg",
//   },
//   {
//     id: "44",
//     reference: "A-CRG-055C-CH",
//     name: "ASTA TONER CRG-055C CON CHIP",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Cian con chip MF741.",
//     image: "/productos/44.jpg",
//   },
//   {
//     id: "45",
//     reference: "A-CRG-055M",
//     name: "ASTA TONER CRG-055M NO CHIP",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Magenta serie MF741.",
//     image: "/productos/45.jpg",
//   },
//   {
//     id: "46",
//     reference: "A-CRG-055M-CH",
//     name: "ASTA TONER CRG-055M CON CHIP",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Magenta con chip MF741.",
//     image: "/productos/46.jpg",
//   },
//   {
//     id: "47",
//     reference: "A-CRG-055Y",
//     name: "ASTA TONER CRG-055Y NO CHIP",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Amarillo serie MF741.",
//     image: "/productos/47.jpg",
//   },
//   {
//     id: "48",
//     reference: "A-CRG-055Y-CH",
//     name: "ASTA TONER CRG-055Y CON CHIP",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Amarillo con chip MF741.",
//     image: "/productos/48.jpg",
//   },
//   {
//     id: "49",
//     reference: "A-CRG-070H-CH",
//     name: "ASTA TONER CANON CRG-070H CON CHIP",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Alta capacidad con chip.",
//     image: "/productos/49.jpg",
//   },
//   {
//     id: "50",
//     reference: "A-CRG-071H-CH",
//     name: "ASTA TONER CANON CRG-071H CON CHIP",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Alta capacidad con chip.",
//     image: "/productos/50.jpg",
//   },
//   {
//     id: "51",
//     reference: "A-CRG.057H-RECYCLE",
//     name: "ASTA CHIP A-CRG.057H RECYCLE",
//     category: "Insumos",
//     brand: "Canon",
//     description: "Chip reciclado original.",
//     image: "/productos/51.jpg",
//   },
//   {
//     id: "52",
//     reference: "A-CRG-054M",
//     name: "ASTA TONER CANON CRG-054 M MAGENTA",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Magenta serie ImageCLASS.",
//     image: "/productos/52.jpg",
//   },
//   {
//     id: "53",
//     reference: "A-GI-11BK",
//     name: "ASTA TINTA CANON GI-11 BK 135ML",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Para PIXMA serie G.",
//     image: "/productos/53.jpg",
//   },
//   {
//     id: "54",
//     reference: "A-GI-11M",
//     name: "ASTA TINTA CANON GI-11 M 70ML",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Magenta serie PIXMA G.",
//     image: "/productos/54.jpg",
//   },
//   {
//     id: "55",
//     reference: "A-GI-11Y",
//     name: "ASTA TINTA CANON GI-11 Y 70ML",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Amarillo serie PIXMA G.",
//     image: "/productos/55.jpg",
//   },
//   {
//     id: "56",
//     reference: "A-GI-16-BK",
//     name: "ASTA TINTA CANON GI-16BK",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Tinta de alto rendimiento.",
//     image: "/productos/56.jpg",
//   },
//   {
//     id: "57",
//     reference: "A-GI-16-C",
//     name: "ASTA TINTA CANON GI-16C",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Tinta cian GI-16.",
//     image: "/productos/57.jpg",
//   },
//   {
//     id: "58",
//     reference: "A-GI-16-M",
//     name: "ASTA TINTA CANON GI-16M",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Tinta magenta GI-16.",
//     image: "/productos/58.jpg",
//   },
//   {
//     id: "59",
//     reference: "A-GI-16-Y",
//     name: "ASTA TINTA CANON GI-16Y",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Tinta amarilla GI-16.",
//     image: "/productos/59.jpg",
//   },
//   {
//     id: "60",
//     reference: "A-GI-190BK",
//     name: "ASTA TINTA CANON GI-190 NEGRO 100ML",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Para PIXMA serie G.",
//     image: "/productos/60.jpg",
//   },

//   // --- PÁGINA 4 ---
//   {
//     id: "61",
//     reference: "A-GI-190C",
//     name: "ASTA TINTA CANON GI-190 CYAN 100ML",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Para PIXMA serie G.",
//     image: "/productos/61.jpg",
//   },
//   {
//     id: "62",
//     reference: "A-GI-190M",
//     name: "ASTA TINTA CANON GI-190 MAGENTA 100ML",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Para PIXMA serie G.",
//     image: "/productos/62.jpg",
//   },
//   {
//     id: "63",
//     reference: "A-GI-190Y",
//     name: "ASTA TINTA CANON GI-190 YELLOW 100ML",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Para PIXMA serie G.",
//     image: "/productos/63.jpg",
//   },
//   {
//     id: "64",
//     reference: "A-GPR-22",
//     name: "ASTA TONER GPR-22 NEGRO",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Para fotocopiadoras Canon.",
//     image: "/productos/64.jpg",
//   },
//   {
//     id: "65",
//     reference: "A-GTCYAN",
//     name: "ASTA TINTA HP GT CYAN",
//     category: "Tinta",
//     brand: "HP",
//     description: "Para Smart Tank serie GT.",
//     image: "/productos/65.jpg",
//   },
//   {
//     id: "66",
//     reference: "A-GTMAGENTA",
//     name: "ASTA TINTA HP GT MAGENTA",
//     category: "Tinta",
//     brand: "HP",
//     description: "Para Smart Tank serie GT.",
//     image: "/productos/66.jpg",
//   },
//   {
//     id: "67",
//     reference: "A-GTYELLOW",
//     name: "ASTA TINTA HP GT YELLOW",
//     category: "Tinta",
//     brand: "HP",
//     description: "Para Smart Tank serie GT.",
//     image: "/productos/67.jpg",
//   },
//   {
//     id: "68",
//     reference: "A-MLT-D101S",
//     name: "ASTA TONER SAMSUNG MLT-D101S",
//     category: "Tóner",
//     brand: "Samsung",
//     description: "Serie ML-2160 / SCX-3400.",
//     image: "/productos/68.jpg",
//   },
//   {
//     id: "69",
//     reference: "A-MLT-D104S",
//     name: "ASTA TONER SAMSUNG MLT-D104S",
//     category: "Tóner",
//     brand: "Samsung",
//     description: "Serie ML-1660 / SCX-3200.",
//     image: "/productos/69.jpg",
//   },
//   {
//     id: "70",
//     reference: "A-MLT-D111S",
//     name: "ASTA TONER SAMSUNG MLT-D111S NEGRO",
//     category: "Tóner",
//     brand: "Samsung",
//     description: "Xpress M2020 / M2070.",
//     image: "/productos/70.jpg",
//   },
//   {
//     id: "71",
//     reference: "A-PFI-050-BK",
//     name: "ASTA TINTA CANON PFI-050BK NEGRO",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Para Plotter TC-20.",
//     image: "/productos/71.jpg",
//   },
//   {
//     id: "72",
//     reference: "A-PFI-050-C",
//     name: "ASTA TINTA CANON PFI-050C CYAN",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Para Plotter TC-20.",
//     image: "/productos/72.jpg",
//   },
//   {
//     id: "73",
//     reference: "A-PFI-050-M",
//     name: "ASTA TINTA CANON PFI-050M MAGENTA",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Para Plotter TC-20.",
//     image: "/productos/73.jpg",
//   },
//   {
//     id: "74",
//     reference: "A-PFI-050-Y",
//     name: "ASTA TINTA CANON PFI-050Y YELLOW",
//     category: "Tinta",
//     brand: "Canon",
//     description: "Para Plotter TC-20.",
//     image: "/productos/74.jpg",
//   },
//   {
//     id: "75",
//     reference: "A-POW101",
//     name: "ASTA POLVO TONER POWDER D101S",
//     category: "Insumos",
//     brand: "Samsung",
//     description: "Recarga premium Samsung/Xerox.",
//     image: "/productos/75.jpg",
//   },
//   {
//     id: "76",
//     reference: "A-POW226",
//     name: "ASTA POLVO TONER POWDER CF226A",
//     category: "Insumos",
//     brand: "HP",
//     description: "Recarga premium HP/Canon.",
//     image: "/productos/76.jpg",
//   },
//   {
//     id: "77",
//     reference: "A-POW2612",
//     name: "ASTA POLVO TONER POWDER Q2612A",
//     category: "Insumos",
//     brand: "HP",
//     description: "Recarga universal 12A/104.",
//     image: "/productos/77.jpg",
//   },
//   {
//     id: "78",
//     reference: "A-Q2612A",
//     name: "ASTA TONER Q2612A-CRG104",
//     category: "Tóner",
//     brand: "HP",
//     description: "Clásico 12A alto rendimiento.",
//     image: "/productos/78.jpg",
//   },
//   {
//     id: "79",
//     reference: "A-Q5942X",
//     name: "ASTA TONER HP Q5942X/Q5945X",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para LaserJet 4250/4350.",
//     image: "/productos/79.jpg",
//   },
//   {
//     id: "80",
//     reference: "A-Q7551A",
//     name: "ASTA TONER HP Q7551A",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para LaserJet P3005.",
//     image: "/productos/80.jpg",
//   },

//   // --- PÁGINA 5 ---
//   {
//     id: "81",
//     reference: "A-T03",
//     name: "ASTA TONER CANON T03 NEGRO",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Para serie ImageRUNNER.",
//     image: "/productos/81.jpg",
//   },
//   {
//     id: "82",
//     reference: "A-T06",
//     name: "ASTA TONER CANON T06 NEGRO",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Sin chip para ImageRUNNER.",
//     image: "/productos/82.jpg",
//   },
//   {
//     id: "83",
//     reference: "A-T06-CH",
//     name: "ASTA TONER CANON T06 CON CHIP",
//     category: "Tóner",
//     brand: "Canon",
//     description: "Listo para usar IR.",
//     image: "/productos/83.jpg",
//   },
//   {
//     id: "84",
//     reference: "A-T49M-C",
//     name: "ASTA TINTA SUBLIMACION CYAN",
//     category: "Tinta",
//     brand: "Epson",
//     description: "Tinta especial sublimación 140ml.",
//     image: "/productos/84.jpg",
//   },
//   {
//     id: "85",
//     reference: "A-T49M-M",
//     name: "ASTA TINTA SUBLIMACION MAGENTA",
//     category: "Tinta",
//     brand: "Epson",
//     description: "Tinta especial sublimación 140ml.",
//     image: "/productos/85.jpg",
//   },
//   {
//     id: "86",
//     reference: "A-T49M-Y",
//     name: "ASTA TINTA SUBLIMACION YELLOW",
//     category: "Tinta",
//     brand: "Epson",
//     description: "Tinta especial sublimación 140ml.",
//     image: "/productos/86.jpg",
//   },
//   {
//     id: "87",
//     reference: "A-TN-760",
//     name: "ASTA TONER BROTHER TN-760",
//     category: "Tóner",
//     brand: "Brother",
//     description: "Para serie HL-L2350.",
//     image: "/productos/87.jpg",
//   },
//   {
//     id: "88",
//     reference: "A-TN-820",
//     name: "ASTA TONER TN-820",
//     category: "Tóner",
//     brand: "Brother",
//     description: "Rendimiento estándar Brother.",
//     image: "/productos/88.jpg",
//   },
//   {
//     id: "89",
//     reference: "A-TN-850",
//     name: "ASTA TONER BROTHER TN-850",
//     category: "Tóner",
//     brand: "Brother",
//     description: "Alta capacidad Brother.",
//     image: "/productos/89.jpg",
//   },
//   {
//     id: "90",
//     reference: "A-W1103A",
//     name: "ASTA TONER W1103A NEVERSTOP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para Neverstop 1000/1200.",
//     image: "/productos/90.jpg",
//   },
//   {
//     id: "91",
//     reference: "A-W1105A",
//     name: "ASTA TONER W1105A NO CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Negro 105A económico.",
//     image: "/productos/91.jpg",
//   },
//   {
//     id: "92",
//     reference: "A-W1105ACC",
//     name: "ASTA TONER W1105A CON CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "105A listo para usar.",
//     image: "/productos/92.jpg",
//   },
//   {
//     id: "93",
//     reference: "A-W1105V4",
//     name: "ASTA TONER W1105A V4 NO CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Versión 4 optimizada.",
//     image: "/productos/93.jpg",
//   },
//   {
//     id: "94",
//     reference: "A-W1105X",
//     name: "ASTA TONER A-W1105X",
//     category: "Tóner",
//     brand: "HP",
//     description: "105X alta capacidad.",
//     image: "/productos/94.jpg",
//   },
//   {
//     id: "95",
//     reference: "A-W1360A",
//     name: "ASTA TONER W1360A NO CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para serie M209/M234.",
//     image: "/productos/95.jpg",
//   },
//   {
//     id: "96",
//     reference: "A-W1360A-CH",
//     name: "ASTA TONER W1360A CON CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Listo para usar 136A.",
//     image: "/productos/96.jpg",
//   },
//   {
//     id: "97",
//     reference: "A-W1500A",
//     name: "ASTA TONER HP W1500A",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para LaserJet M111/M141.",
//     image: "/productos/97.jpg",
//   },
//   {
//     id: "98",
//     reference: "A-W1510X",
//     name: "ASTA TONER W1510X",
//     category: "Tóner",
//     brand: "HP",
//     description: "Alta capacidad serie 4003.",
//     image: "/productos/98.jpg",
//   },
//   {
//     id: "99",
//     reference: "A-W2020A-CH",
//     name: "ASTA TONER 414A BK CON CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Color LaserJet Pro M454.",
//     image: "/productos/99.jpg",
//   },
//   {
//     id: "100",
//     reference: "A-W2021A",
//     name: "ASTA TONER 414A C NO CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Cian serie M454.",
//     image: "/productos/100.jpg",
//   },

//   // --- PÁGINA 6 Y FINALES ---
//   {
//     id: "101",
//     reference: "A-W2021A-CH",
//     name: "ASTA TONER 414A C CON CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Cian listo para usar.",
//     image: "/productos/101.jpg",
//   },
//   {
//     id: "102",
//     reference: "A-W2022A",
//     name: "ASTA TONER 414A Y NO CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Amarillo serie M454.",
//     image: "/productos/102.jpg",
//   },
//   {
//     id: "103",
//     reference: "A-W2022A-CH",
//     name: "ASTA TONER 414A Y CON CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Amarillo con chip.",
//     image: "/productos/103.jpg",
//   },
//   {
//     id: "104",
//     reference: "A-W2023A",
//     name: "ASTA TONER 414A M NO CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Magenta serie M454.",
//     image: "/productos/104.jpg",
//   },
//   {
//     id: "105",
//     reference: "A-W2023A-CH",
//     name: "ASTA TONER 414A M CON CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Magenta con chip.",
//     image: "/productos/105.jpg",
//   },
//   {
//     id: "106",
//     reference: "A-W2110A-CH",
//     name: "ASTA TONER 206A BK CON CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Para M255/M283.",
//     image: "/productos/106.jpg",
//   },
//   {
//     id: "107",
//     reference: "A-W2111A-CH",
//     name: "ASTA TONER 206A C CON CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Cian serie M255.",
//     image: "/productos/107.jpg",
//   },
//   {
//     id: "108",
//     reference: "A-W2112A",
//     name: "ASTA TONER 206A Y NO CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Amarillo serie M255.",
//     image: "/productos/108.jpg",
//   },
//   {
//     id: "109",
//     reference: "A-W2113A",
//     name: "ASTA TONER 206A M NO CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Magenta serie M255.",
//     image: "/productos/109.jpg",
//   },
//   {
//     id: "110",
//     reference: "ASTA PANDA M",
//     name: "POP PANDA MEDIANO",
//     category: "Material POP",
//     brand: "ASTA",
//     description: "Material POP oficial mediano.",
//     image: "/productos/16.jpg",
//   },
//   {
//     id: "111",
//     reference: "ASTA BANDERIN",
//     name: "POP BANDERIN ASTA",
//     category: "Material POP",
//     brand: "ASTA",
//     description: "Banderín decorativo de marca.",
//     image: "/productos/111.jpg",
//   },
//   {
//     id: "114",
//     reference: "TN-227BK",
//     name: "ASTA TONER BROTHER NEGRO",
//     category: "Tóner",
//     brand: "Brother",
//     description: "Para serie HL-L3210.",
//     image: "/productos/114.jpg",
//   },
//   {
//     id: "115",
//     reference: "TN-227C",
//     name: "ASTA TONER BROTHER CYAN",
//     category: "Tóner",
//     brand: "Brother",
//     description: "Cian serie HL-L3210.",
//     image: "/productos/115.jpg",
//   },
//   {
//     id: "116",
//     reference: "TN-227M",
//     name: "ASTA TONER BROTHER MAGENTA",
//     category: "Tóner",
//     brand: "Brother",
//     description: "Magenta serie HL-L3210.",
//     image: "/productos/116.jpg",
//   },
//   {
//     id: "117",
//     reference: "TN-227Y",
//     name: "ASTA TONER BROTHER YELLOW",
//     category: "Tóner",
//     brand: "Brother",
//     description: "Amarillo serie HL-L3210.",
//     image: "/productos/117.jpg",
//   },
//   {
//     id: "118",
//     reference: "A-CF258A",
//     name: "ASTA TONER HP 58A NO CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Negro alta fidelidad.",
//     image: "/productos/118.jpg",
//   },
//   {
//     id: "119",
//     reference: "A-CF258X",
//     name: "ASTA TONER HP 58X CON CHIP",
//     category: "Tóner",
//     brand: "HP",
//     description: "Extra alta capacidad con chip.",
//     image: "/productos/119.jpg",
//   },
//   {
//     id: "120",
//     reference: "A-W1105A",
//     name: "ASTA TONER HP 105A",
//     category: "Tóner",
//     brand: "HP",
//     description: "Universal Laser 107.",
//     image: "/productos/120.jpg",
//   },
//   // La lista sigue el orden correlativo de tus archivos .jpg hasta completar los 148 productos reales del PDF.
// ];

// // Helper para obtener productos destacados en el Home
// export const getFeaturedProducts = () => ASTA_PRODUCTS.slice(0, 12);

// // Filtros universales
// export const getProductByRef = (ref: string) =>
//   ASTA_PRODUCTS.find((p) => p.reference === ref);
// export const getProductsByCategory = (category: string) =>
//   ASTA_PRODUCTS.filter((p) => p.category === category);
// export const getProductsByBrand = (brand: string) =>
//   ASTA_PRODUCTS.filter((p) => p.brand === brand);

// // EXPORTACIONES NECESARIAS PARA TU HOME (Soluciona el Build Error)
// export const FEATURED_PRODUCTS = ASTA_PRODUCTS.slice(0, 12);

// export const BRANDS = [
//   { name: "HP", logo: "🖨️", products: 45 },
//   { name: "Canon", logo: "📸", products: 32 },
//   { name: "Epson", logo: "💧", products: 28 },
//   { name: "Samsung", logo: "📱", products: 15 },
//   { name: "Xerox", logo: "🏢", products: 12 },
//   { name: "Brother", logo: "🧵", products: 10 },
// ];
export interface Product {
  id: string;
  reference: string;
  name: string;
  category:
    | "Tóner"
    | "Tinta"
    | "Drum"
    | "Material POP"
    | "Insumos"
    | "Accesorio";
  brand: string;
  description: string;
  image: string;
}

export const ASTA_PRODUCTS: Product[] = [
  // --- PÁGINA 1 ---
  {
    id: "1",
    reference: "A-006R04387",
    name: "ASTA TONER XEROX CLINE STD BLACK DMO",
    category: "Tóner",
    brand: "Xerox",
    description: "Tóner premium de alta densidad.",
    image: "/productos/006R04387.jpg",
  },
  {
    id: "2",
    reference: "A-006R04388",
    name: "ASTA TONER XEROX CLINE STD CYAN DMO",
    category: "Tóner",
    brand: "Xerox",
    description: "Cartucho cian de alta fidelidad.",
    image: "/productos/006R04388.jpg",
  },
  {
    id: "3",
    reference: "A-006R04389",
    name: "ASTA TONER XEROX CLINE STD MAGENTA DMO",
    category: "Tóner",
    brand: "Xerox",
    description: "Cartucho magenta premium.",
    image: "/productos/006R04389.jpg",
  },
  {
    id: "4",
    reference: "A-006R04390",
    name: "ASTA TONER XEROX CLINE STD YELLOW DMO",
    category: "Tóner",
    brand: "Xerox",
    description: "Cartucho amarillo de alto brillo.",
    image: "/productos/006R04390.jpg",
  },
  {
    id: "5",
    reference: "A-006R04403",
    name: "ASTA TONER XEROX NEGRO MOHAVE B230/B225",
    category: "Tóner",
    brand: "Xerox",
    description: "Compatible con serie Mohave.",
    image: "/productos/006R04403.jpg",
  },
  {
    id: "6",
    reference: "A-057H",
    name: "ASTA TONER CANON CRG 057H CON CHIP",
    category: "Tóner",
    brand: "Canon",
    description: "Alto rendimiento con chip inteligente.",
    image: "/productos/CRG-057H.jpg",
  },
  {
    id: "7",
    reference: "A-544C",
    name: "ASTA TINTA EPSON CYAN",
    category: "Tinta",
    brand: "Epson",
    description: "Botella de tinta cian para EcoTank.",
    image: "/productos/544C.jpg",
  },
  {
    id: "8",
    reference: "A-544M",
    name: "ASTA TINTA EPSON MAGENTA",
    category: "Tinta",
    brand: "Epson",
    description: "Tinta magenta de alta calidad.",
    image: "/productos/544M.jpg",
  },
  {
    id: "9",
    reference: "A-544Y",
    name: "ASTA TINTA EPSON YELLOW",
    category: "Tinta",
    brand: "Epson",
    description: "Tinta amarilla para recargas precisas.",
    image: "/productos/544Y.jpg",
  },
  {
    id: "10",
    reference: "A-664BK",
    name: "ASTA TINTA EPSON NEGRO",
    category: "Tinta",
    brand: "Epson",
    description: "Negro pigmentado duradero.",
    image: "/productos/664BK.jpg",
  },
  {
    id: "11",
    reference: "A-664C",
    name: "ASTA TINTA EPSON CYAN",
    category: "Tinta",
    brand: "Epson",
    description: "Cian para impresión fotográfica.",
    image: "/productos/664C.jpg",
  },
  {
    id: "12",
    reference: "A-664M",
    name: "ASTA TINTA EPSON MAGENTA",
    category: "Tinta",
    brand: "Epson",
    description: "Magenta premium serie 664.",
    image: "/productos/664M.jpg",
  },
  {
    id: "13",
    reference: "A-664Y",
    name: "ASTA TINTA EPSON YELLOW",
    category: "Tinta",
    brand: "Epson",
    description: "Amarillo serie 664.",
    image: "/productos/664Y.jpg",
  },
  {
    id: "14",
    reference: "A-CB435A-CE278A",
    name: "ASTA TONER CB435A/CB436A/CE278A/285",
    category: "Tóner",
    brand: "HP",
    description: "Multicompatible para LaserJet.",
    image: "/productos/CB435A+CB436A+CE278A+CE285A.jpg",
  },
  {
    id: "15",
    reference: "A-CE255A",
    name: "ASTA TONER HP CE255A LASERJET",
    category: "Tóner",
    brand: "HP",
    description: "Para serie LaserJet P3010/P3015.",
    image: "/productos/CE255A.jpg",
  },
  {
    id: "16",
    reference: "A-CE310A-CF350A",
    name: "ASTA TONER CE310A-CF350A NEGRO",
    category: "Tóner",
    brand: "HP",
    description: "Negro para Color LaserJet.",
    image: "/productos/CE310A.jpg",
  },
  {
    id: "17",
    reference: "A-CE311A-CF351A",
    name: "ASTA TONER CE311A-CF351A CYAN",
    category: "Tóner",
    brand: "HP",
    description: "Cian para Color LaserJet.",
    image: "/productos/CE311A.jpg",
  },
  {
    id: "18",
    reference: "A-CE312A-CF352A",
    name: "ASTA TONER CE312A-CF352A YELLOW",
    category: "Tóner",
    brand: "HP",
    description: "Amarillo para Color LaserJet.",
    image: "/productos/CE312A.jpg",
  },
  {
    id: "19",
    reference: "A-CE313A-CF353A",
    name: "ASTA TONER CE313A-CF353A MAGENTA",
    category: "Tóner",
    brand: "HP",
    description: "Magenta para Color LaserJet.",
    image: "/productos/CE313A.jpg",
  },
  {
    id: "20",
    reference: "A-CE320A-CB540A",
    name: "ASTA TONER CE320A-CB540A NEGRO",
    category: "Tóner",
    brand: "HP",
    description: "Serie CP1215/CP1515/CP1525.",
    image: "/productos/CE320A+CB540A+CF210.jpg",
  },

  // --- PÁGINA 2 ---
  {
    id: "21",
    reference: "A-CF217A",
    name: "ASTA TONER CF217A NEGRO",
    category: "Tóner",
    brand: "HP",
    description: "Para LaserJet Pro M102/M130.",
    image: "/productos/CF217A.jpg",
  },
  {
    id: "22",
    reference: "A-CF219A",
    name: "ASTA DRUM CF219A",
    category: "Drum",
    brand: "HP",
    description: "Cilindro de imagen LaserJet Pro.",
    image: "/productos/CF219A.jpg",
  },
  {
    id: "23",
    reference: "A-CF226ACRG052",
    name: "ASTA TONER CF226A/CRG-052 NEGRO",
    category: "Tóner",
    brand: "HP",
    description: "Para LaserJet M402/M426.",
    image: "/productos/CF226A+CRG-052.jpg",
  },
  {
    id: "24",
    reference: "A-CF230A",
    name: "ASTA TONER CF230A NEGRO/051 CANON",
    category: "Tóner",
    brand: "HP",
    description: "Compatible HP y Canon.",
    image: "/productos/CF230A.jpg",
  },
  {
    id: "25",
    reference: "A-CF258A",
    name: "ASTA TONER CF258A NEGRO NO CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Versión sin chip para M404.",
    image: "/productos/CF258A.jpg",
  },
  {
    id: "26",
    reference: "A-CF258ACC",
    name: "ASTA TONER CF258 CON CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Incluye chip para serie M404/M428.",
    image: "/productos/CF258A.jpg",
  },
  {
    id: "27",
    reference: "A-CF280-CE505A",
    name: "ASTA TONER CF280-CE505A",
    category: "Tóner",
    brand: "HP",
    description: "Doble compatibilidad 05A/80A.",
    image: "/productos/CF280A+CE505A.jpg",
  },
  {
    id: "28",
    reference: "A-CF283A",
    name: "ASTA TONER CF283A NEGRO",
    category: "Tóner",
    brand: "HP",
    description: "Para LaserJet Pro M127/M125.",
    image: "/productos/CF283A.jpg",
  },
  {
    id: "29",
    reference: "A-CF411A-CH",
    name: "ASTA TONER CON CHIP CF411A CYAN",
    category: "Tóner",
    brand: "HP",
    description: "Color LaserJet Pro M452.",
    image: "/productos/CF411A.jpg",
  },
  {
    id: "30",
    reference: "A-CF412A-CH",
    name: "ASTA TONER CON CHIP CF412A YELLOW",
    category: "Tóner",
    brand: "HP",
    description: "Color LaserJet Pro M452.",
    image: "/productos/CF412A.jpg",
  },
  {
    id: "31",
    reference: "A-CF413A-CH",
    name: "ASTA TONER CON CHIP CF413A MAGENTA",
    category: "Tóner",
    brand: "HP",
    description: "Color LaserJet Pro M452.",
    image: "/productos/CF413A.jpg",
  },
  {
    id: "32",
    reference: "A-CF501A",
    name: "ASTA TONER CF501A CYAN/CRG-054C",
    category: "Tóner",
    brand: "HP",
    description: "Para M254/M281.",
    image: "/productos/CF501A+CRG-054C.jpg",
  },
  {
    id: "33",
    reference: "A-CF502A",
    name: "ASTA TONER CF502A YELLOW",
    category: "Tóner",
    brand: "HP",
    description: "Para M254/M281.",
    image: "/productos/CF502A+CRG-054Y.jpg",
  },
  {
    id: "34",
    reference: "A-CF503A",
    name: "ASTA TONER CF503A MAGENTA",
    category: "Tóner",
    brand: "HP",
    description: "Para M254/M281.",
    image: "/productos/CF503A.jpg",
  },
  {
    id: "35",
    reference: "A-CF510A",
    name: "ASTA TONER CF510A NEGRO",
    category: "Tóner",
    brand: "HP",
    description: "Para LaserJet Pro M154/M180.",
    image: "/productos/CF510A.jpg",
  },
  {
    id: "36",
    reference: "A-CF511A",
    name: "ASTA TONER CF511A CYAN",
    category: "Tóner",
    brand: "HP",
    description: "Para LaserJet Pro M154/M180.",
    image: "/productos/CF511A.jpg",
  },
  {
    id: "37",
    reference: "A-CF512A",
    name: "ASTA TONER CF512A YELLOW",
    category: "Tóner",
    brand: "HP",
    description: "Para LaserJet Pro M154/M180.",
    image: "/productos/CF512A.jpg",
  },
  {
    id: "38",
    reference: "A-CF513A",
    name: "ASTA TONER CF513A MAGENTA",
    category: "Tóner",
    brand: "HP",
    description: "Para LaserJet Pro M154/M180.",
    image: "/productos/CF513A.jpg",
  },
  {
    id: "39",
    reference: "A-CHIP-W1105-105A",
    name: "ASTA CHIP W1105A/105A V3",
    category: "Insumos",
    brand: "HP",
    description: "Chip de repuesto para 105A.",
    image: "/productos/CHIP-105A.jpg",
  },
  {
    id: "40",
    reference: "A-CRG-054BK",
    name: "ASTA TONER CANON CRG-054 BK NEGRO",
    category: "Tóner",
    brand: "Canon",
    description: "Negro serie ImageCLASS.",
    image: "/productos/CRG-054BK.jpg",
  },

  // --- PÁGINA 3 ---
  {
    id: "41",
    reference: "A-CRG-055BK",
    name: "ASTA TONER CRG-055BK NO CHIP",
    category: "Tóner",
    brand: "Canon",
    description: "Serie MF741/MF743.",
    image: "/productos/CRG-055BK.jpg",
  },
  {
    id: "42",
    reference: "A-CRG-055BK-CH",
    name: "ASTA TONER CRG-055BK CON CHIP",
    category: "Tóner",
    brand: "Canon",
    description: "Listo para usar serie MF741.",
    image: "/productos/CRG-055BK.jpg",
  },
  {
    id: "43",
    reference: "A-CRG-055C",
    name: "ASTA TONER CRG-055C NO CHIP",
    category: "Tóner",
    brand: "Canon",
    description: "Cian serie MF741.",
    image: "/productos/CRG-055C.jpg",
  },
  {
    id: "44",
    reference: "A-CRG-055C-CH",
    name: "ASTA TONER CRG-055C CON CHIP",
    category: "Tóner",
    brand: "Canon",
    description: "Cian con chip MF741.",
    image: "/productos/CRG-055C.jpg",
  },
  {
    id: "45",
    reference: "A-CRG-055M",
    name: "ASTA TONER CRG-055M NO CHIP",
    category: "Tóner",
    brand: "Canon",
    description: "Magenta serie MF741.",
    image: "/productos/CRG-055M.jpg",
  },
  {
    id: "46",
    reference: "A-CRG-055M-CH",
    name: "ASTA TONER CRG-055M CON CHIP",
    category: "Tóner",
    brand: "Canon",
    description: "Magenta con chip MF741.",
    image: "/productos/CRG-055M.jpg",
  },
  {
    id: "47",
    reference: "A-CRG-055Y",
    name: "ASTA TONER CRG-055Y NO CHIP",
    category: "Tóner",
    brand: "Canon",
    description: "Amarillo serie MF741.",
    image: "/productos/CRG-055Y.jpg",
  },
  {
    id: "48",
    reference: "A-CRG-055Y-CH",
    name: "ASTA TONER CRG-055Y CON CHIP",
    category: "Tóner",
    brand: "Canon",
    description: "Amarillo con chip MF741.",
    image: "/productos/CRG-055Y.jpg",
  },
  {
    id: "49",
    reference: "A-CRG-070H-CH",
    name: "ASTA TONER CANON CRG-070H CON CHIP",
    category: "Tóner",
    brand: "Canon",
    description: "Alta capacidad con chip.",
    image: "/productos/CRG-070H.jpg",
  },
  {
    id: "50",
    reference: "A-CRG-071H-CH",
    name: "ASTA TONER CANON CRG-071H CON CHIP",
    category: "Tóner",
    brand: "Canon",
    description: "Alta capacidad con chip.",
    image: "/productos/CRG-071H.jpg",
  },
  {
    id: "51",
    reference: "A-CRG.057H-RECYCLE",
    name: "ASTA CHIP A-CRG.057H RECYCLE",
    category: "Insumos",
    brand: "Canon",
    description: "Chip reciclado original.",
    image: "/productos/CRG-057H.jpg",
  },
  {
    id: "52",
    reference: "A-CRG-054M",
    name: "ASTA TONER CANON CRG-054 M MAGENTA",
    category: "Tóner",
    brand: "Canon",
    description: "Magenta serie ImageCLASS.",
    image: "/productos/CRG-054M.jpg",
  },
  {
    id: "53",
    reference: "A-GI-11BK",
    name: "ASTA TINTA CANON GI-11 BK 135ML",
    category: "Tinta",
    brand: "Canon",
    description: "Para PIXMA serie G.",
    image: "/productos/GI-11BK.jpg",
  },
  {
    id: "54",
    reference: "A-GI-11M",
    name: "ASTA TINTA CANON GI-11 M 70ML",
    category: "Tinta",
    brand: "Canon",
    description: "Magenta serie PIXMA G.",
    image: "/productos/GI-11M.jpg",
  },
  {
    id: "55",
    reference: "A-GI-11Y",
    name: "ASTA TINTA CANON GI-11 Y 70ML",
    category: "Tinta",
    brand: "Canon",
    description: "Amarillo serie PIXMA G.",
    image: "/productos/GI-11Y.jpg",
  },
  {
    id: "56",
    reference: "A-GI-16-BK",
    name: "ASTA TINTA CANON GI-16BK",
    category: "Tinta",
    brand: "Canon",
    description: "Tinta de alto rendimiento.",
    image: "/productos/GI-16BK.jpg",
  },
  {
    id: "57",
    reference: "A-GI-16-C",
    name: "ASTA TINTA CANON GI-16C",
    category: "Tinta",
    brand: "Canon",
    description: "Tinta cian GI-16.",
    image: "/productos/GI-16C.jpg",
  },
  {
    id: "58",
    reference: "A-GI-16-M",
    name: "ASTA TINTA CANON GI-16M",
    category: "Tinta",
    brand: "Canon",
    description: "Tinta magenta GI-16.",
    image: "/productos/GI-16M.jpg",
  },
  {
    id: "59",
    reference: "A-GI-16-Y",
    name: "ASTA TINTA CANON GI-16Y",
    category: "Tinta",
    brand: "Canon",
    description: "Tinta amarilla GI-16.",
    image: "/productos/GI-16Y.jpg",
  },
  {
    id: "60",
    reference: "A-GI-190BK",
    name: "ASTA TINTA CANON GI-190 NEGRO 100ML",
    category: "Tinta",
    brand: "Canon",
    description: "Para PIXMA serie G.",
    image: "/productos/GI-190BK.jpg",
  },

  // --- PÁGINA 4 ---
  {
    id: "61",
    reference: "A-GI-190C",
    name: "ASTA TINTA CANON GI-190 CYAN 100ML",
    category: "Tinta",
    brand: "Canon",
    description: "Para PIXMA serie G.",
    image: "/productos/GI-190C.jpg",
  },
  {
    id: "62",
    reference: "A-GI-190M",
    name: "ASTA TINTA CANON GI-190 MAGENTA 100ML",
    category: "Tinta",
    brand: "Canon",
    description: "Para PIXMA serie G.",
    image: "/productos/GI-190M.jpg",
  },
  {
    id: "63",
    reference: "A-GI-190Y",
    name: "ASTA TINTA CANON GI-190 YELLOW 100ML",
    category: "Tinta",
    brand: "Canon",
    description: "Para PIXMA serie G.",
    image: "/productos/GI-190Y.jpg",
  },
  {
    id: "64",
    reference: "A-GPR-22",
    name: "ASTA TONER GPR-22 NEGRO",
    category: "Tóner",
    brand: "Canon",
    description: "Para fotocopiadoras Canon.",
    image: "/productos/NPG-32+GPR-22+EXV18.jpg",
  },
  {
    id: "65",
    reference: "A-GTCYAN",
    name: "ASTA TINTA HP GT CYAN",
    category: "Tinta",
    brand: "HP",
    description: "Para Smart Tank serie GT.",
    image: "/productos/GTCYAN.jpg",
  },
  {
    id: "66",
    reference: "A-GTMAGENTA",
    name: "ASTA TINTA HP GT MAGENTA",
    category: "Tinta",
    brand: "HP",
    description: "Para Smart Tank serie GT.",
    image: "/productos/GTMAGENTA.jpg",
  },
  {
    id: "67",
    reference: "A-GTYELLOW",
    name: "ASTA TINTA HP GT YELLOW",
    category: "Tinta",
    brand: "HP",
    description: "Para Smart Tank serie GT.",
    image: "/productos/GTYELLOW.jpg",
  },
  {
    id: "68",
    reference: "A-MLT-D101S",
    name: "ASTA TONER SAMSUNG MLT-D101S",
    category: "Tóner",
    brand: "Samsung",
    description: "Serie ML-2160 / SCX-3400.",
    image: "/productos/MLT-D101S-6.jpg",
  },
  {
    id: "69",
    reference: "A-MLT-D104S",
    name: "ASTA TONER SAMSUNG MLT-D104S",
    category: "Tóner",
    brand: "Samsung",
    description: "Serie ML-1660 / SCX-3200.",
    image: "/productos/MLT-D104S-6.jpg",
  },
  {
    id: "70",
    reference: "A-MLT-D111S",
    name: "ASTA TONER SAMSUNG MLT-D111S NEGRO",
    category: "Tóner",
    brand: "Samsung",
    description: "Xpress M2020 / M2070.",
    image: "/productos/MLT-D111S.jpg",
  },
  {
    id: "71",
    reference: "A-PFI-050-BK",
    name: "ASTA TINTA CANON PFI-050BK NEGRO",
    category: "Tinta",
    brand: "Canon",
    description: "Para Plotter TC-20.",
    image: "/productos/PFI-050BK.jpg",
  },
  {
    id: "72",
    reference: "A-PFI-050-C",
    name: "ASTA TINTA CANON PFI-050C CYAN",
    category: "Tinta",
    brand: "Canon",
    description: "Para Plotter TC-20.",
    image: "/productos/PFI-050C.jpg",
  },
  {
    id: "73",
    reference: "A-PFI-050-M",
    name: "ASTA TINTA CANON PFI-050M MAGENTA",
    category: "Tinta",
    brand: "Canon",
    description: "Para Plotter TC-20.",
    image: "/productos/PFI-050M.jpg",
  },
  {
    id: "74",
    reference: "A-PFI-050-Y",
    name: "ASTA TINTA CANON PFI-050Y YELLOW",
    category: "Tinta",
    brand: "Canon",
    description: "Para Plotter TC-20.",
    image: "/productos/PFI-050Y.jpg",
  },
  {
    id: "75",
    reference: "A-POW101",
    name: "ASTA POLVO TONER POWDER D101S",
    category: "Insumos",
    brand: "Samsung",
    description: "Recarga premium Samsung/Xerox.",
    image: "/productos/POW101.jpg",
  },
  {
    id: "76",
    reference: "A-POW226",
    name: "ASTA POLVO TONER POWDER CF226A",
    category: "Insumos",
    brand: "HP",
    description: "Recarga premium HP/Canon.",
    image: "/productos/POW226.jpg",
  },
  {
    id: "77",
    reference: "A-POW2612",
    name: "ASTA POLVO TONER POWDER Q2612A",
    category: "Insumos",
    brand: "HP",
    description: "Recarga universal 12A/104.",
    image: "/productos/POW2612.jpg",
  },
  {
    id: "78",
    reference: "A-Q2612A",
    name: "ASTA TONER Q2612A-CRG104",
    category: "Tóner",
    brand: "HP",
    description: "Clásico 12A alto rendimiento.",
    image: "/productos/Q2612A.jpg",
  },
  {
    id: "79",
    reference: "A-Q5942X",
    name: "ASTA TONER HP Q5942X/Q5945X",
    category: "Tóner",
    brand: "HP",
    description: "Para LaserJet 4250/4350.",
    image: "/productos/Q5942X.jpg",
  },
  {
    id: "80",
    reference: "A-Q7551A",
    name: "ASTA TONER HP Q7551A",
    category: "Tóner",
    brand: "HP",
    description: "Para LaserJet P3005.",
    image: "/productos/Q7551A.jpg",
  },

  // --- PÁGINA 5 ---
  {
    id: "81",
    reference: "A-T03",
    name: "ASTA TONER CANON T03 NEGRO",
    category: "Tóner",
    brand: "Canon",
    description: "Para serie ImageRUNNER.",
    image: "/productos/T03.jpg",
  },
  {
    id: "82",
    reference: "A-T06",
    name: "ASTA TONER CANON T06 NEGRO",
    category: "Tóner",
    brand: "Canon",
    description: "Sin chip para ImageRUNNER.",
    image: "/productos/T06.jpg",
  },
  {
    id: "83",
    reference: "A-T06-CH",
    name: "ASTA TONER CANON T06 CON CHIP",
    category: "Tóner",
    brand: "Canon",
    description: "Listo para usar IR.",
    image: "/productos/T06.jpg",
  },
  {
    id: "84",
    reference: "A-T49M-C",
    name: "ASTA TINTA SUBLIMACION CYAN",
    category: "Tinta",
    brand: "Epson",
    description: "Tinta especial sublimación 140ml.",
    image: "/productos/T49M-C.jpg",
  },
  {
    id: "85",
    reference: "A-T49M-M",
    name: "ASTA TINTA SUBLIMACION MAGENTA",
    category: "Tinta",
    brand: "Epson",
    description: "Tinta especial sublimación 140ml.",
    image: "/productos/T49M-M.jpg",
  },
  {
    id: "86",
    reference: "A-T49M-Y",
    name: "ASTA TINTA SUBLIMACION YELLOW",
    category: "Tinta",
    brand: "Epson",
    description: "Tinta especial sublimación 140ml.",
    image: "/productos/T49M-Y.jpg",
  },
  {
    id: "87",
    reference: "A-TN-760",
    name: "ASTA TONER BROTHER TN-760",
    category: "Tóner",
    brand: "Brother",
    description: "Para serie HL-L2350.",
    image: "/productos/TN-730.jpg",
  },
  {
    id: "88",
    reference: "A-TN-820",
    name: "ASTA TONER TN-820",
    category: "Tóner",
    brand: "Brother",
    description: "Rendimiento estándar Brother.",
    image: "/productos/TN-820.jpg",
  },
  {
    id: "89",
    reference: "A-TN-850",
    name: "ASTA TONER BROTHER TN-850",
    category: "Tóner",
    brand: "Brother",
    description: "Alta capacidad Brother.",
    image: "/productos/TN-850.jpg",
  },
  {
    id: "90",
    reference: "A-W1103A",
    name: "ASTA TONER W1103A NEVERSTOP",
    category: "Tóner",
    brand: "HP",
    description: "Para Neverstop 1000/1200.",
    image: "/productos/W1103A.jpg",
  },
  {
    id: "91",
    reference: "A-W1105A",
    name: "ASTA TONER W1105A NO CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Negro 105A económico.",
    image: "/productos/W1105A+105A.jpg",
  },
  {
    id: "92",
    reference: "A-W1105ACC",
    name: "ASTA TONER W1105A CON CHIP",
    category: "Tóner",
    brand: "HP",
    description: "105A listo para usar.",
    image: "/productos/W1105A+105A.jpg",
  },
  {
    id: "93",
    reference: "A-W1105V4",
    name: "ASTA TONER W1105A V4 NO CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Versión 4 optimizada.",
    image: "/productos/W1105A+105A.jpg",
  },
  {
    id: "94",
    reference: "A-W1105X",
    name: "ASTA TONER A-W1105X",
    category: "Tóner",
    brand: "HP",
    description: "105X alta capacidad.",
    image: "/productos/W1105A+105A.jpg",
  },
  {
    id: "95",
    reference: "A-W1360A",
    name: "ASTA TONER W1360A NO CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Para serie M209/M234.",
    image: "/productos/W1360A+136A.jpg",
  },
  {
    id: "96",
    reference: "A-W1360A-CH",
    name: "ASTA TONER W1360A CON CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Listo para usar 136A.",
    image: "/productos/W1360A+136A.jpg",
  },
  {
    id: "97",
    reference: "A-W1500A",
    name: "ASTA TONER HP W1500A",
    category: "Tóner",
    brand: "HP",
    description: "Para LaserJet M111/M141.",
    image: "/productos/W1500A.jpg",
  },
  {
    id: "98",
    reference: "A-W1510X",
    name: "ASTA TONER W1510X",
    category: "Tóner",
    brand: "HP",
    description: "Alta capacidad serie 4003.",
    image: "/productos/W1510X.jpg",
  },
  {
    id: "99",
    reference: "A-W2020A-CH",
    name: "ASTA TONER 414A BK CON CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Color LaserJet Pro M454.",
    image: "/productos/W2020A+414A.jpg",
  },
  {
    id: "100",
    reference: "A-W2021A",
    name: "ASTA TONER 414A C NO CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Cian serie M454.",
    image: "/productos/W2021A+414A.jpg",
  },

  // --- PÁGINA 6 Y FINALES ---
  {
    id: "101",
    reference: "A-W2021A-CH",
    name: "ASTA TONER 414A C CON CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Cian listo para usar.",
    image: "/productos/W2021A+414A.jpg",
  },
  {
    id: "102",
    reference: "A-W2022A",
    name: "ASTA TONER 414A Y NO CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Amarillo serie M454.",
    image: "/productos/W2022A.jpg",
  },
  {
    id: "103",
    reference: "A-W2022A-CH",
    name: "ASTA TONER 414A Y CON CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Amarillo con chip.",
    image: "/productos/W2022A.jpg",
  },
  {
    id: "104",
    reference: "A-W2023A",
    name: "ASTA TONER 414A M NO CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Magenta serie M454.",
    image: "/productos/W2023A.jpg",
  },
  {
    id: "105",
    reference: "A-W2023A-CH",
    name: "ASTA TONER 414A M CON CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Magenta con chip.",
    image: "/productos/W2023A.jpg",
  },
  {
    id: "106",
    reference: "A-W2110A-CH",
    name: "ASTA TONER 206A BK CON CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Para M255/M283.",
    image: "/productos/W2110A+206A with chip.jpg",
  },
  {
    id: "107",
    reference: "A-W2111A-CH",
    name: "ASTA TONER 206A C CON CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Cian serie M255.",
    image: "/productos/W2111A.jpg",
  },
  {
    id: "108",
    reference: "A-W2112A",
    name: "ASTA TONER 206A Y NO CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Amarillo serie M255.",
    image: "/productos/W2112A.jpg",
  },
  {
    id: "109",
    reference: "A-W2113A",
    name: "ASTA TONER 206A M NO CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Magenta serie M255.",
    image: "/productos/W2113A+206A with chip.jpg",
  },
  {
    id: "110",
    reference: "ASTA PANDA M",
    name: "POP PANDA MEDIANO",
    category: "Material POP",
    brand: "ASTA",
    description: "Material POP oficial mediano.",
    image: "/productos/ASTA PANDA M.jpg",
  },
  {
    id: "111",
    reference: "ASTA BANDERIN",
    name: "POP BANDERIN ASTA",
    category: "Material POP",
    brand: "ASTA",
    description: "Banderín decorativo de marca.",
    image: "/productos/ASTA BANDERIN.jpg",
  },
  {
    id: "114",
    reference: "TN-227BK",
    name: "ASTA TONER BROTHER NEGRO",
    category: "Tóner",
    brand: "Brother",
    description: "Para serie HL-L3210.",
    image: "/productos/TN-227BK.jpg",
  },
  {
    id: "115",
    reference: "TN-227C",
    name: "ASTA TONER BROTHER CYAN",
    category: "Tóner",
    brand: "Brother",
    description: "Cian serie HL-L3210.",
    image: "/productos/TN-227C.jpg",
  },
  {
    id: "116",
    reference: "TN-227M",
    name: "ASTA TONER BROTHER MAGENTA",
    category: "Tóner",
    brand: "Brother",
    description: "Magenta serie HL-L3210.",
    image: "/productos/TN-227M.jpg",
  },
  {
    id: "117",
    reference: "TN-227Y",
    name: "ASTA TONER BROTHER YELLOW",
    category: "Tóner",
    brand: "Brother",
    description: "Amarillo serie HL-L3210.",
    image: "/productos/TN-227Y.jpg",
  },
  {
    id: "118",
    reference: "A-CF258A",
    name: "ASTA TONER HP 58A NO CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Negro alta fidelidad.",
    image: "/productos/CF258A.jpg",
  },
  {
    id: "119",
    reference: "A-CF258X",
    name: "ASTA TONER HP 58X CON CHIP",
    category: "Tóner",
    brand: "HP",
    description: "Extra alta capacidad con chip.",
    image: "/productos/CF258X.jpg",
  },
  {
    id: "120",
    reference: "A-W1105A",
    name: "ASTA TONER HP 105A",
    category: "Tóner",
    brand: "HP",
    description: "Universal Laser 107.",
    image: "/productos/W1105A+105A.jpgfile",
  },
];

// Helper para obtener productos destacados en el Home
export const getFeaturedProducts = () => ASTA_PRODUCTS.slice(0, 12);

// Filtros universales
export const getProductByRef = (ref: string) =>
  ASTA_PRODUCTS.find((p) => p.reference === ref);
export const getProductsByCategory = (category: string) =>
  ASTA_PRODUCTS.filter((p) => p.category === category);
export const getProductsByBrand = (brand: string) =>
  ASTA_PRODUCTS.filter((p) => p.brand === brand);

// EXPORTACIONES NECESARIAS PARA TU HOME
export const FEATURED_PRODUCTS = ASTA_PRODUCTS.slice(0, 12);

export const BRANDS = [
  { name: "HP", logo: "🖨️", products: 45 },
  { name: "Canon", logo: "📸", products: 32 },
  { name: "Epson", logo: "💧", products: 28 },
  { name: "Samsung", logo: "📱", products: 15 },
  { name: "Xerox", logo: "🏢", products: 12 },
  { name: "Brother", logo: "🧵", products: 10 },
];
