export const FEATURED_PRODUCTS = [
  {
    id: 'A-W1105A',
    name: 'Tóner HP W1105A',
    category: 'Tóneres HP',
    description: 'Tóner compatible para HP LaserJet con máximo rendimiento y calidad de impresión superior.',
    price: 18.50,
    stock: 196,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/74-cxUdFsDi2YxTuY9NpgGtLLbzr0EcTS.jpg',
    specs: {
      compatibilidad: 'HP LaserJet',
      rendimiento: 'Hasta 10,200 páginas',
      tipo: 'Tóner Negro',
    },
  },
  {
    id: 'A-CRG-055BK-CH',
    name: 'Tóner Canon CRG-055',
    category: 'Tóneres Canon',
    description: 'Tóner de calidad premium para impresoras Canon con chip inteligente incluido.',
    price: 39.95,
    stock: 77,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/71-yMCAmasjpzZQG3mDEbIToziUVqyfUA.jpg',
    specs: {
      compatibilidad: 'Canon imageRUNNER',
      rendimiento: 'Hasta 15,000 páginas',
      tipo: 'Tóner Negro con Chip',
    },
  },
  {
    id: 'A-GI-190BK',
    name: 'Tinta Canon GI-190',
    category: 'Tintas Canon',
    description: 'Tinta de tinta continua para impresoras Canon PIXMA con excelente saturación de color.',
    price: 6.10,
    stock: 557,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/73-07626ecbhEbK4tfbdMG3xCGmW8peHl.jpg',
    specs: {
      compatibilidad: 'Canon PIXMA',
      volumen: '100 ML',
      tipo: 'Tinta Negro',
    },
  },
  {
    id: 'A-MLT-D101S',
    name: 'Tóner Samsung MLT-D101S',
    category: 'Tóneres Samsung',
    description: 'Tóner compatible para impresoras Samsung con rendimiento excepcional.',
    price: 18.50,
    stock: 24,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/72-QfXE2hRfsqNpoA6aZ3mdIsz97bbrIK.jpg',
    specs: {
      compatibilidad: 'Samsung ML-2160/2165/2166',
      rendimiento: 'Hasta 1,500 páginas',
      tipo: 'Tóner Negro',
    },
  },
  {
    id: 'A-CF258A-CH',
    name: 'Tóner HP CF258A',
    category: 'Tóneres HP',
    description: 'Tóner inteligente HP con chip para impresoras LaserJet Pro.',
    price: 23.95,
    stock: 194,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/75-fzmVGLXDW70ShprbPaOy2fl86cezyi.jpg',
    specs: {
      compatibilidad: 'HP LaserJet Pro M404/M428',
      rendimiento: 'Hasta 3,100 páginas',
      tipo: 'Tóner Negro con Chip',
    },
  },
  {
    id: 'A-TN-820',
    name: 'Tóner Brother TN-820',
    category: 'Tóneres Brother',
    description: 'Tóner original Brother con máximo rendimiento para tus impresoras.',
    price: 23.95,
    stock: 3,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/70-l6C6DNuhfRGWNtQQCIeTHdjgATpecZN.jpg',
    specs: {
      compatibilidad: 'Brother HL-L8360/DCP-L8410',
      rendimiento: 'Hasta 3,000 páginas',
      tipo: 'Tóner Negro',
    },
  },
  {
    id: 'A-544C',
    name: 'Tinta Epson Cyan',
    category: 'Tintas Epson',
    description: 'Tinta de sublimación Epson de alta calidad para máxima saturación de color.',
    price: 1.40,
    stock: 129,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/75-fzmVGLXDW70ShprbPaOy2fl86cezyi.jpg',
    specs: {
      compatibilidad: 'Epson L-Series',
      volumen: 'Botella estándar',
      tipo: 'Tinta Cyan',
    },
  },
  {
    id: 'A-Q2612A',
    name: 'Tóner HP Q2612A',
    category: 'Tóneres HP',
    description: 'Clásico tóner HP con excelente relación precio-rendimiento.',
    price: 14.50,
    stock: 90,
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/72-QfXE2hRfsqNpoA6aZ3mdIsz97bbrIK.jpg',
    specs: {
      compatibilidad: 'HP LaserJet 1010/1012/1015',
      rendimiento: 'Hasta 2,000 páginas',
      tipo: 'Tóner Negro',
    },
  },
];

export const PRODUCT_CATEGORIES = [
  { name: 'Tóneres HP', count: 45 },
  { name: 'Tóneres Canon', count: 32 },
  { name: 'Tóneres Brother', count: 12 },
  { name: 'Tóneres Samsung', count: 8 },
  { name: 'Tóneres Xerox', count: 6 },
  { name: 'Tintas Canon', count: 28 },
  { name: 'Tintas Epson', count: 18 },
  { name: 'Tintas HP', count: 15 },
  { name: 'Accesorios', count: 20 },
  { name: 'Consumibles', count: 50 },
];

export const BRANDS = [
  { name: 'HP', logo: '🖨️', products: 120 },
  { name: 'Canon', logo: '📷', products: 85 },
  { name: 'Brother', logo: '📄', products: 45 },
  { name: 'Samsung', logo: '⭐', products: 30 },
  { name: 'Epson', logo: '✨', products: 40 },
  { name: 'Xerox', logo: '🔷', products: 25 },
  { name: 'Lexmark', logo: '📊', products: 20 },
  { name: 'Ricoh', logo: '🎯', products: 15 },
];
